Add rewriters chain loading by configuration (backwards compatibility) #Issue76
querqy/querqy pull request #139
Opened 2021-01-22 15:01 UTC by tkaessmann

As part of the #76 it's now possible to still parse the deprecated rewriters configuration (instead of the new REST interface). If you want to use this, you have to move the rewriters configuration to a listener in the solrconfig like:

```xml
<listener event="firstSearcher" class="querqy.solr.ClassicRewriteChainLoader">  
   <lst name="rewriteChain">
      <lst name="rewriter">
      ...
      </lst name="rewriter">
   </lst name="rewriteChain">
</listener>
```
And set the `inMemory` configuration in the new request handler:
```xml
<requestHandler name="/querqy/rewriter" class="querqy.solr.QuerqyRewriterRequestHandler">
   <bool name="inMemory">true</bool>
</requestHandler>
```
thanks also to @tboeghk

2021-01-26 07:42 UTC, renekrie requested changes

2021-01-26 07:42 UTC, tboeghk commented
@tkaessmann note to self: Let's merge the master into this PR to resolve future merge and testing hell :-/

2021-01-27 18:24 UTC, renekrie approved these changes
Please take note of the comments. I'm going to approve the PR and resolve a few minor things myself.

2021-01-27 18:24 UTC, renekrie commented on querqy-for-lucene/querqy-solr/src/main/java/querqy/solr/ClassicRewriteChainLoader.java
> +                        req.setContentStreams(newArrayList(new ContentStreamBase.StringStream(JsonUtil.toJson(jsonBody), UTF_8.name())));
newArrayList - this list can be immutable. We can simply use https://docs.oracle.com/javase/6/docs/api/java/util/Collections.html#singletonList(T) and get rid of the Guava dependency at the same go.

2021-01-27 18:24 UTC, renekrie commented on querqy-for-lucene/querqy-solr/src/main/java/querqy/solr/QuerqyQParserPlugin.java
> +                    "You have to move it to a Querqy listener or change the rewriter deployment. See upgrade info.");
Let's mention the concrete Listener class in the error message

2021-01-27 18:24 UTC, renekrie commented on querqy-for-lucene/querqy-solr/src/main/java/querqy/solr/QuerqyQParserPlugin.java
> +                    rewriterRequestHandlerName + " is not a " + QuerqyRewriterRequestHandler.class);
QuerqyRewriterRequestHandler.class.getName() ...

2021-01-27 18:24 UTC, renekrie commented on querqy-for-lucene/querqy-solr/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> +mock-maker-inline
Wow! I didn't know that we can mock final classes!

2021-01-27 18:25 UTC, renekrie commented
Thank you @tkaessmann  & @tboeghk

2021-01-27 18:26 UTC, merged