Issue 187 - Explain API
querqy/querqy pull request #251
Opened 2021-11-01 13:21 UTC by worleydl

Initial changes to add the explain API.

TODO:

- [ ] Build out tests
- [ ] Move SnapshotRewriter code to querqy-core

2021-11-01 14:04 UTC, epugh commented
Does this all get dumped out in the Solr debug or is this a new thing?    I'd love to expose this in Quepid...

2021-11-01 14:06 UTC, renekrie commented
@epugh It's a new HTTP endpoint: #187

2021-11-01 14:33 UTC, renekrie requested changes
ExplainRewriter: Please deal with BoostedTerm and with Term.value property name. Nice to have: use constants where possible

2021-11-01 14:33 UTC, renekrie commented on querqy-for-lucene/querqy-solr/src/main/java/querqy/solr/explain/SnapshotRewriter.java
> +            props.put("term", term.toString());
`term` and `generated' could be constants

2021-11-01 14:33 UTC, renekrie commented on querqy-for-lucene/querqy-solr/src/main/java/querqy/solr/explain/SnapshotRewriter.java
> +        public Void visit(final Term term) {
`term` could also be of type `BoostedTerm` in that case we should add the boost to the snapshot

2021-11-01 14:33 UTC, renekrie commented on querqy-for-lucene/querqy-solr/src/main/java/querqy/solr/explain/SnapshotRewriter.java
> +                props.put("field", term.getField());
make 'field' a constant

2021-11-01 14:33 UTC, renekrie commented on querqy-for-lucene/querqy-solr/src/main/java/querqy/solr/explain/SnapshotRewriter.java
> +            props.put("term", term.toString());
I think we should rather use " props.put("value", term.toString());"

2021-11-02 21:07 UTC, mkr commented on querqy-for-lucene/querqy-solr/src/main/java/querqy/solr/explain/SnapshotRewriter.java
> +import org.graalvm.compiler.lir.phases.PreAllocationOptimizationPhase;
Unused import ;)

2021-11-03 17:06 UTC, renekrie approved these changes

2021-11-03 18:24 UTC, renekrie approved these changes

2021-11-03 18:24 UTC, renekrie commented
Thank you @worleydl !

2021-11-03 18:24 UTC, merged